// <auto-generated />
using System;
using Barista.Offers.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Barista.Offers.Migrations
{
    [DbContext(typeof(OffersDbContext))]
    [Migration("20190401085231_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Barista.Offers.Domain.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("Created");

                    b.Property<Guid>("PointOfSaleId");

                    b.Property<Guid>("ProductId");

                    b.Property<decimal?>("RecommendedPrice");

                    b.Property<Guid?>("StockItemId");

                    b.Property<DateTimeOffset>("Updated");

                    b.Property<DateTimeOffset?>("ValidSince");

                    b.Property<DateTimeOffset?>("ValidUntil");

                    b.HasKey("Id");

                    b.ToTable("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
