// <auto-generated />
using System;
using Barista.Consistency.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Barista.Consistency.Migrations
{
    [DbContext(typeof(ConsistencyDbContext))]
    partial class ConsistencyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Barista.Consistency.Domain.ScheduledEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("Created");

                    b.Property<string>("MessageTypeName");

                    b.Property<DateTimeOffset>("ScheduledFor");

                    b.Property<string>("SerializedContents");

                    b.Property<DateTimeOffset>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledFor");

                    b.ToTable("ScheduledEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
